static_page/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home' #erisim url
  get 'pages/about' #erisim url/pages/about
  get 'pages/products' #erisim url/pages/products
  get 'pages/form' #erisim url/pages/form
  get 'pages/help' #erisim url/pages/help
  get 'pages/authenticate' #erisim url/pages/authenticate
  get 'pages/logout' #erisim url/pages/authenticate
  get 'pages/edit' #erisim url/pages/authenticate
  get 'users/login' #erisim url/pages/help
  resources :pages
  resources :users
  end

static_page/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

static_page/app/models/page.rb
class Page < ApplicationRecord
end

static_page/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true
  validates :password, presence: true
  validates :username, length: {minimum: 3}
  validates :password, length: {minimum: 3}
end

static_page/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

static_page/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def products
    @page = Page.all
  end

  def form
    @page = Page.new
  end

  def help

  end

  def create
    @page = Page.create(page_params)
    if @page.save
      flash[:success] = "You created a new post"
      redirect_to pages_products_path
    else
      flash[:danger] = "There was an error"
      render :form
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(post_params)
      flash[:success] = "Post updated."
      redirect_to @page
    else
      flash[:danger] = "There was an error when updating."
      render :edit
    end
  end

  def show
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to root_path
  end

  def logout

  end

  private def page_params
    params.require(:page).permit(:title, :body)
  end



end

static_page/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    @user = User.new
  end

  def create
    @user = User.find_by(username: user_params[:username].downcase)
    @pas = User.find_by(password: user_params[:password].downcase)
    if @user && @pas
      session[:user_id] = @user.id
      flash[:success] = "You Signed Up woo!"
      redirect_to '/pages/authenticate'
    else
      flash[:danger] = "There was an error try again!"
      render :login
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url
  end


  def user_params
    params.require(:user).permit(:username, :password)
  end


end

static_page/app/helpers/application_helper.rb
module ApplicationHelper
end

static_page/app/helpers/pages_helper.rb
module PagesHelper
end

static_page/app/helpers/users_helper.rb
module UsersHelper
end

static_page/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaticPage</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css' %>
  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Home', root_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'About', pages_about_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" <%= link_to 'Products', pages_products_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" <%= link_to 'Form', pages_form_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" <%= link_to 'Help', pages_help_path %> </a>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled" <%= link_to 'Login', users_login_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" <%= link_to 'Logout',pages_logout_path  %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br>
<br>
<br>
<br>
<% flash.each do |name, message| %>
  <%= content_tag :div, message, class: "alert alert-#{name}" %>
<% end %>
<%= yield %>

<footer>
  <p>Copyright <%= Date.current.year %></p>
</footer>

</body>
</html>

static_page/app/views/pages/about.html.erb
<h1>About</h1>
<%= link_to 'HOME', root_path %>

static_page/app/views/pages/authenticate.html.erb
<h1>User Login</h1>

static_page/app/views/pages/edit.html.erb
<h1>Edit</h1>

static_page/app/views/pages/form.html.erb
<br>
<h1>Form</h1>
<%= form_for @page do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

static_page/app/views/pages/help.erb
<h1>Help</h1>

static_page/app/views/pages/home.html.erb
<main role="main" class="container">
  <div class="starter-template">
    <h1>Home Page</h1>
    <p class="lead">
      Cool Fancy Text Generator is a copy and paste font changer that creates Twitter, Facebook, Instagram fonts. It
      converts a normal text to different free cool fonts styles, such as tattoo fonts, calligraphy fonts, web script
      fonts,
      cursive fonts, handwriting fonts, old English fonts, word fonts, pretty fonts, font art... Instagram Fonts or
      Fonts
      for Instagram - If that is what you want then this tool is a perfect place to go because it provides more than
      that!
      Basically, Cool Text Generator a cute copy and paste font generator online, font maker, font creator, font
      changer,
      special text maker, stylish text generator, weird text generator, word art generator, fancy letter generator,
      webfont
      generator, signature maker, signature creator, free text symbols generator, logo animation maker, font manager...
      This
      tool helps generate text symbols, cool Unicode fancy letters, fancy writing, fancy fonts, stylish fonts, cool
      symbols,
      cool symbol text, emoji, fancy letters, letter fonts, funky cool text, fancy chat message, fancy facebook status,
      fancy nick, love text, beautiful ASCII text art, text pictures, emoticons, emoji text... with different serif,
      sans-serif font types.
    </p>
  </div>
</main>

static_page/app/views/pages/logout.html.erb
<h1>Logout</h1>

static_page/app/views/pages/products.erb
<h1>Products</h1>

<% @page.each do |p| %>
  <p class="title"><%= p.title %></p>
  <p class="body"><%= p.body %></p>
  <%= link_to "Edit Post", edit_page_path(p) %>
  <%= link_to "Show Post", pages_products_path(p) %>
<% end %>

static_page/app/views/users/login.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col‐md‐6 col‐md‐offset‐3">
      <%= form_for @user do |f| %>
        <div class="form‐group">
          <%= f.text_field :username, :placeholder => "Name" , class: 'form‐control' %>
        </div>
        <div class="form‐group">
          <%= f.password_field :password, :placeholder => "Password" , class:'form‐control' %>
        </div>
        <%= f.submit "Submit" , class: 'btn btn‐primary' %>
      <% end %>
    </div>
  </div>
</div>